### ISSUE TITLE
Blog issue

### ISSUE THREAD

**Issue by malys** [andryanmiller/frontendian#11]
Hi,
FYI. French version of your CORS post is unavailable.
https://frontendian.co/fr_FR/cors ->302 https://fr.frontendian-prod.now.sh/cors.html ->  SSL_ERROR_INTERNAL_ERROR_ALERT (Firefox, Chrome).

Bye and thx for writing excellent post.

**Comment by andryanmiller** [comment]
Sorry for the long response time @malys! This issue should be addressed, thanks for letting me know!
